SAMPLE_RATE = 16000
CHANNELS = 1

AUDIO_BLOCK_SEC = 0.1
MIN_SPEECH_SEC = 0.3
SILENCE_END_SEC = 0.3

WHISPER_MODEL = "tiny"
WHISPER_COMPUTE_TYPE = "int8"

TOP_K = 3
CONFIRM_DESTRUCTIVE = True

LOG_PATH = "assistant.log"
ACTIONS_JSON_PATH = "data/actions.json"
